### ISSUE TITLE
User Interface approach

### ISSUE THREAD

**Issue by nyue** [fzipp/canvas#2]
Hi,

  I would like to build a simple diagramming application where the bulk of the 2D drawing are done in canvas.

  For the UI (I am looking to use buttons, dropdown menus, slider bars, check boxes and text/numeric fields), what libraries would work well with canvas ?

Cheers

**Comment by fzipp** [comment]
Hi,

thanks for your interest in this project.

It would certainly be possible to implement a simple UI widget library on top of this module, but something like that doesn't exist yet. I only very recently released this project to the public. I don't think a lot of people use it right now, and I am not aware of any libraries built on top of it.

There are GUI toolkit efforts for Go like [Fyne](https://fyne.io) or [Gio](https://gioui.org) that use native rendering backends, and of course Go bindings for toolkits like GTK exist.

I could also imagine a project similar to this that uses WebSockets to communicate with HTML DOM elements in a browser, for example form input elements, but that would be a different project.
